### ISSUE TITLE
ValueError: can not merge DataFrame with instance of type <class 'pandas.core.series.Series'>

### ISSUE THREAD

**Issue by SreenidhiKalyan** [DP6/Marketing-Attribution-Models#3]
I have used the inbuilt random df provided in the code. When Group_channels= True, in the part of Grouping the timestamp, Value ERROR is thrown

**Comment by rsennes** [comment]
Hi @SreenidhiKalyan, this error still persists? I saw you already closed...

Do you want to share any feedback about the usability? Tks
