### ISSUE TITLE
how to change the code to pass the conversion_value from the dataset?

### ISSUE THREAD

**Issue by SreenidhiKalyan** [DP6/Marketing-Attribution-Models#4]

**Comment by kayleighm** [comment]
Hi, @SreenidhiKalyan! 
You can use the "conversion_value" parameter. 
It's set 1 by default, but also receive a string indicating the column name on the dataset containing the conversion values.

**Comment by SreenidhiKalyan** [comment]
attributions  =  MAM ( df,
     group_channels = True ,
     channels_colname  =  "act" ,
     journey_with_conv_colname =  'has_converted' ,
     group_channels_by_id_list = [ 'phone' ],
     group_timestamp_colname  =  'date' ,
     **conversion_value='Previous',**
     create_journey_id_based_on_conversion  =  True)

I'm passing string Previous which is a column name from my dataframe indicating the conversion value. The datatype of conversion_value is float.
On executing attributions.DataFrame(), the conversion value is displayed as 0.0
Exact conversion value is not appearing in the column conversion_value

**Comment by andretocci** [comment]
Hi @SreenidhiKalyan, thanks for the informations.

With your contribution we were able to find the bug that was causing the problem and fix it. The parameter group_channels = True wasn't aggregating the conversion_value properly.

We've updated a new version on Pypl. Could you try again after updating the package?

Thanks!

**Comment by SreenidhiKalyan** [comment]
You can close this reply

**Comment by rsennes** [comment]
Thanks @SreenidhiKalyan. Don't hesitate to report in any issue.
