### ISSUE TITLE
Acrescentar suporte a coluna journey_with_conv_colname contendo int64 (0 e 1) quando "create_journey_id_based_on_conversion=True"

### ISSUE THREAD

**Issue by luisrizzardi** [DP6/Marketing-Attribution-Models#51]
Quando o usuário especifica o argumento "create_journey_id_based_on_conversion=True" e a sua coluna que indica as conversões (journey_with_conv_colname) está preenchida com 0 e 1 (int64), a MAM exibe um erro ao rodar a função df.where(...) dentro da função    journey_id_based_on_conversion.

Na função journey_id_based_on_conversion, uma cópia do DF é criado para realizar as operações necessárias. Para dar suporte a estes casos, podemos converter a coluna journey_with_conv_colname para booleano apenas na cópia do DF dentro da função, sem prejuízo para o restante do código.
![Exemplo do erro exibido - FR MAM](https://user-images.githubusercontent.com/49167306/148287617-7dea7524-0e72-4c0b-ae3d-10d74708270f.png)

**Comment by Nathandsn** [comment]
Issue resolvido no commit #48 alterando o tipo da coluna para 'bool' quando especificado "create_journey_id_based_on_conversion=True".
