### ISSUE TITLE
Uso dos modelos de atribuição.

### ISSUE THREAD

**Issue by FranciscohAlpa** [DP6/Marketing-Attribution-Models#7]
Prezados, tudo bem ?

  Fiquei com uma dúvida referente ao uso dos modelos de atribuição em relação ao revenue. Como são utilizados os modelos heurísticos (First e last touch) e o removal effect (modelo baseado na cadeia de Markov) em relação ao revenue ? Faço essa pergunta porque não necessariamente a soma do removal effect irá ser 1, se atribuirmos diretamente as proporções deste ao revenue as somas das atribuições poderá ser maior que soma do próprio revenue.

Grato.

**Comment by andretocci** [comment]
Olá Francisco, tudo bem?

Utilizamos o valor do removal effect normalizado para re-atribuir os valores das conversões por canal e caso haja _self.conversion_value_, multiplicamos esse valor normalizado pela soma do self.conversion_value.

```python
removal_effect_result / removal_effect_result.sum(axis=0) 
```

Era isso mesmo a sua dúvida?

Qualquer outra questão, estamos à disposição!

Att

**Comment by FranciscohAlpa** [comment]
Olá André, tudo sim e com você?

Sim era essa minha dúvida, muito obrigado pelo retorno. Desculpa se pareceu
meio "idiota" a questão, sou novo no "mundo" de Marketing e não tinha
encontrado nada a respetio. A informação sempre pará, em por exemplo:
"Pronto temos um modelo heurístico de last click" sem descrever como
utilizar na prática sabe.

Eu agradeço muito seu retorno. E parabéns pelo pacote. Não sei se você tem
conhecimento do software R, ele também tem muitos pacotes interessantes em
relação  a  atribuição de mídia digital.

Grato,
-------------------------------------
*Francisco Hildemar*
Cientista de dados
Cel.: +55 85 9 9766 6934
-------------------------------------


Em sex., 13 de nov. de 2020 às 13:55, André Tocci <notifications@github.com>
escreveu:

**Comment by andretocci** [comment]
Olá Francisco, tudo bem?

Não existe perguntas "idiotas", são todas são validas, ainda mais para alguém que está aprendendo! 

Se quiser saber um pouco mais sobre o mundo do Marketing + Data Science, recomendo dar uma olhada no [Blog da DP6](https://blog.dp6.com.br/). Temos artigos detalhando um pouco melhor os diferentes modelos de atribuição, além de outros temas relacionados.

Quanto ao software R, utilizamos os pacotes GameTheoryAllocation e o ChannelAttribution como referência durante a implementação.

Qualquer dúvida, estamos à disposição! 

Att,

**Comment by FranciscohAlpa** [comment]
Olá André, tudo bem sim e com você?

Obrigado pelo retorno e indicação do blog. Escrevi uma nova dúvida lá no
git.

Seria essa:
Fiquei com uma dúvida ao uso dos modelos de atribuíção heurísticos. Por
exemplo, rodando um modelo de atribuição baseado no first click, temos como
resposta a coluna "attribution_first_click_heuristic" que me parece trazer
as frequências das mídias de first click para jornada de conversão. Como
usar o valor dessa coluna para re-atribuir os valores das conversões por
canal ?

Muito parecida com a anterior onde perguntei sobre o uso do removal effect.

Grato,
-------------------------------------
*Francisco Hildemar*
Cientista de dados
Cel.: +55 85 9 9766 6934
-------------------------------------


Em ter., 17 de nov. de 2020 às 15:23, André Tocci <notifications@github.com>
escreveu:
