### ISSUE TITLE
Uso dos modelos de atribuição heurísticos

### ISSUE THREAD

**Issue by FranciscohAlpa** [DP6/Marketing-Attribution-Models#8]
Prezados, boa tarde, tudo bem ?

Fiquei com uma dúvida ao uso dos modelos de atribuíção heurísticos. Por exemplo, rodando um modelo de atribuição baseado no first click, temos como resposta a coluna "attribution_first_click_heuristic" que me parece trazer as frequências das mídias de first click para jornada de conversão. Como usar o valor dessa coluna  para re-atribuir os valores das conversões por canal ? 

Grato.

**Comment by andretocci** [comment]
Francisco, tudo bem?

Acessando o atributo _group_by_channels_models_, você tem acesso aos valores atribuídos agrupado pelos canais da sua base de dados. 

Então se um canal esteve presente em 3 jornadas, mas em só duas foi o ultimo ponto de contato. Analisando os resultados em _group_by_channels_models_ para o modelo _last click_, iremos observar um valor atribuído de 2 conversões.

Era essa a sua dúvida?

Atenciosamente,

**Comment by FranciscohAlpa** [comment]
Olá André, tudo bem ?

Obrigado pelo retorno. Ficou claro agora.

Grato.
-------------------------------------
*Francisco Hildemar*
Cientista de dados
Cel.: +55 85 9 9766 6934
-------------------------------------


Em ter., 24 de nov. de 2020 às 19:44, André Tocci <notifications@github.com>
escreveu:
